name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push mysql
        uses: docker/build-push-action@v3
        with:
          file: docker_mysql/Dockerfile
          context: .
          push: true
          tags: vivianachan/ia-center-mysql:mysql-${{ github.sha }}
          
      - name: Build and push fast api
        uses: docker/build-push-action@v3
        with:
          file: docker_fastapi/Dockerfile
          context: .
          push: true
          tags: vivianachan/ia-center-fast-api:fastapi-${{ github.sha }}

